import { Message } from "./types";

export const welcomeMessages: Message[] = [
  {
    id: "welcome-1",
    username: "sorcerer",
    role: "admin",
    text: `📨 Welcome to Your 3-Day Trial — I'm Freya Quinn

Hey, I'm Freya 👋
I'm a UK-based trader and systems builder.
Since you're reading this, you've passed the basic verification and officially entered the trial.
Good choice 🫡

🍀 A quick note about me
I've spent the last few years building an automated, rule-based trading approach —
inspired by growing up around structured thinkers (my father worked in quantitative finance for decades).

I'm not here to promise perfection or magic.
Markets can't be mastered — only respected.
But a disciplined system can beat emotions — and that's exactly what this channel is built on ⚙️📊

🔥 What You'll Get in This 3-Day Trial

You'll receive automated signals on major assets:

🥇 Gold (XAU)
🛢️ USOIL
💵 USDJPY
📉 DJI30
📊 NASDAQ (NDX)
🇩🇪 GER40
🪙 BTC
✨ ETH`,
    timestamp: Date.now() - 3600000,
    avatar: "F",
  },
];

export const moneyGlitchMessages: Message[] = [
  {
    id: "signal-1",
    username: "sorcerer",
    role: "admin",
    text: `script : USOUSD
Position : BUY ⬆️
Enter Price : 60.244
Take Profit 1 : 60.490
Take Profit 2 : 60.653
Take Profit 3 : 60.899
Take Profit 4 : 61.227
Stoploss : 59.835`,
    timestamp: Date.now() - 7200000,
    avatar: "F",
  },
  {
    id: "signal-2",
    username: "sorcerer",
    role: "admin",
    text: `script : DJI30
Position : BUY ⬆️
Enter Price : 48058.68
Take Profit 1 : 48174.43
Take Profit 2 : 48251.60
Take Profit 3 : 48367.35
Take Profit 4 : 48521.69
Stoploss : 47965.76`,
    timestamp: Date.now() - 5400000,
    avatar: "F",
  },
  {
    id: "signal-3",
    username: "sorcerer",
    role: "admin",
    text: `script : XAUUSD
Position : BUY ⬆️
Enter Price : 4197.78
Take Profit 1 : 4201.47
Take Profit 2 : 4203.94
Take Profit 3 : 4207.63
Take Profit 4 : 4212.56
Stoploss : 4191.62`,
    timestamp: Date.now() - 3600000,
    avatar: "F",
  },
];

export const reviewsMessages: Message[] = [
  {
    id: "review-1",
    username: "sorcerer",
    role: "admin",
    text: `⭐ Member Reviews

Here's what our members are saying:`,
    timestamp: Date.now() - 86400000,
    avatar: "F",
  },
  {
    id: "review-2",
    username: "TraderMike",
    text: `Made 11.4% in 2 days 🔥
This is insane. Never seen such consistent signals.`,
    timestamp: Date.now() - 82800000,
    avatar: "M",
  },
  {
    id: "review-3",
    username: "CryptoSarah",
    text: `Best automated system I've tried
Been in trading for 5 years. This beats everything else I've used. The risk management is top tier.`,
    timestamp: Date.now() - 79200000,
    avatar: "C",
  },
  {
    id: "review-4",
    username: "ForexKing",
    text: `Finally a channel that doesn't spam entries
Quality over quantity. Every signal is well-researched. Hit TP2 on 4 out of 5 trades this week 🎯`,
    timestamp: Date.now() - 75600000,
    avatar: "F",
  },
];

export const howItWorksMessages: Message[] = [
  {
    id: "how-1",
    username: "sorcerer",
    role: "admin",
    text: `⚙️ How The System Works

My automated trading system is built on 3 core principles:

1️⃣ **Rule-Based Entries**
No emotions. No guessing.
Every signal is generated by a quantitative model that scans:
• Price action patterns
• Volume analysis
• Market structure
• Risk-reward ratios

2️⃣ **Multi-Layered Risk Control**
Each signal comes with:
• 4 Take Profit levels (TP1-TP4)
• Strict stop loss
• Position sizing guidance
• Risk never exceeds 2% per trade

3️⃣ **Automated Execution**
Signals are sent automatically when conditions are met.
No delays. No manual intervention.
You get the entry price, TPs, and SL instantly.`,
    timestamp: Date.now() - 3600000,
    avatar: "F",
  },
  {
    id: "how-2",
    username: "sorcerer",
    role: "admin",
    text: `📊 Signal Structure

Every signal follows this format:

**Script**: Asset name (XAUUSD, BTCUSD, etc.)
**Position**: BUY ⬆️ or SELL ⬇️
**Enter Price**: Exact entry point
**Take Profit 1-4**: Multiple exit levels
**Stoploss**: Maximum risk point

Why 4 TPs?
• TP1: Quick profit (conservative)
• TP2: Medium target (most common)
• TP3: Extended move
• TP4: Maximum potential

This lets you scale out and lock profits progressively.`,
    timestamp: Date.now() - 1800000,
    avatar: "F",
  },
  {
    id: "how-3",
    username: "sorcerer",
    role: "admin",
    text: `🧠 Why It Beats Human Emotions

The biggest enemy in trading isn't the market.
It's your emotions.

Fear → Exits too early
Greed → Holds too long
Revenge → Overtrades after loss
FOMO → Chases bad entries

My system eliminates all of that.

It follows the same rules every single time.
No panic. No euphoria. Just execution.

That's why it outperforms 90% of manual traders.`,
    timestamp: Date.now() - 900000,
    avatar: "F",
  },
];

export const liveResultsMessages: Message[] = [
  {
    id: "results-1",
    username: "sorcerer",
    role: "admin",
    text: `📈 Live Results (Last 7 Days)

Here's the performance breakdown:

✅ XAUUSD - BUY
Entry: 4185.20
TP2 Hit: 4192.50 ✅
Result: +73 pips 🟢

✅ USDJPY - SELL
Entry: 149.85
TP3 Hit: 149.20 ✅
Result: +65 pips 🟢

✅ BTCUSD - BUY
Entry: 94,200
TP1 Hit: 95,100 ✅
Result: +900 points 🟢

❌ DJI30 - BUY
Entry: 48,100
SL Hit: 47,950 ❌
Result: -150 points 🔴

✅ USOIL - SELL
Entry: 71.50
TP2 Hit: 70.80 ✅
Result: +70 pips 🟢`,
    timestamp: Date.now() - 3600000,
    avatar: "F",
  },
  {
    id: "results-2",
    username: "sorcerer",
    role: "admin",
    text: `📊 Win Rate: 80% (4 wins / 1 loss)

Average Risk-Reward: 1:2.8

Total Profit: +1,008 pips/points
Total Loss: -150 pips/points
Net: +858 pips/points

This is typical performance.
Not every trade wins, but the system ensures winners are bigger than losers.

That's how you stay profitable long-term.`,
    timestamp: Date.now() - 1800000,
    avatar: "F",
  },
];

export const sneakPeekMessages: Message[] = [
  {
    id: "peek-1",
    username: "sorcerer",
    role: "admin",
    text: `👀 Sneak Peek - Real Trade Examples

Here are some recent winning trades from the full channel:`,
    timestamp: Date.now() - 3600000,
    avatar: "F",
  },
  {
    id: "peek-2",
    username: "sorcerer",
    role: "admin",
    text: `🎯 XAUUSD Trade

Entry: 4197.78
TP1 Hit: 4201.47 ✅
TP2 Hit: 4203.94 ✅

Members who took this made +$420 per lot.

Clean entry. Clean exit. No stress.`,
    timestamp: Date.now() - 2700000,
    avatar: "F",
  },
  {
    id: "peek-3",
    username: "sorcerer",
    role: "admin",
    text: `🎯 BTCUSD Trade

Entry: 96,500
TP1 Hit: 97,200 ✅
TP2 Hit: 97,800 ✅
TP3 Hit: 98,500 ✅

+$1,300 per BTC.

This is what happens when you let the system work.`,
    timestamp: Date.now() - 1800000,
    avatar: "F",
  },
  {
    id: "peek-4",
    username: "sorcerer",
    role: "admin",
    text: `🎯 USDJPY Trade

Entry: 150.20
TP1 Hit: 149.85 ✅
TP2 Hit: 149.50 ✅

+70 pips in 4 hours.

Fast. Efficient. Profitable.`,
    timestamp: Date.now() - 900000,
    avatar: "F",
  },
];

export const faqMessages: Message[] = [
  {
    id: "faq-1",
    username: "sorcerer",
    role: "admin",
    text: `❓ Frequently Asked Questions

**Q: Is this real?**
A: Yes. These are real signals from a quantitative trading system I've built over 3+ years. The preview shows actual signal format and quality.

**Q: What is the minimum capital?**
A: Recommended minimum is $500 for forex/commodities, $1,000 for crypto. This allows proper risk management (1-2% per trade).

**Q: Are the signals manual or automated?**
A: Fully automated. The system scans markets 24/7 and sends signals when conditions are met. No human delay.`,
    timestamp: Date.now() - 3600000,
    avatar: "F",
  },
  {
    id: "faq-2",
    username: "sorcerer",
    role: "admin",
    text: `**Q: Is there a refund policy?**
A: The 3-day trial is free. After that, if you're not satisfied within the first 7 days of paid membership, full refund. No questions asked.

**Q: Is this legal in my country?**
A: Trading signals are legal in most countries. However, you're responsible for checking your local regulations. We don't provide financial advice—just automated signals.

**Q: How many signals per day?**
A: Typically 3-8 signals per day across all assets. Quality over quantity. We don't spam entries.`,
    timestamp: Date.now() - 1800000,
    avatar: "F",
  },
  {
    id: "faq-3",
    username: "sorcerer",
    role: "admin",
    text: `**Q: Do I need trading experience?**
A: No. Signals are clear and easy to follow. However, basic understanding of how to place orders on your broker is recommended.

**Q: What broker do you recommend?**
A: Any reputable broker works. We don't endorse specific brokers. Use one you trust with good spreads and execution.

**Q: Can I automate the trades?**
A: Yes. Advanced members use copy trading or APIs to automate execution. We provide guidance in the full channel.`,
    timestamp: Date.now() - 900000,
    avatar: "F",
  },
];
